apps/todo/views.py
from flask import Blueprint, render_template, redirect, url_for, current_app, send_from_directory, request,jsonify, flash
from flask_login import login_required, current_user
from apps.todo.models import UserTodo
from apps.todo.forms import TodoCreateForm, TodoEditForm
from apps.crud.models import User
import string
import random
from apps.app import db
import datetime

todo = Blueprint(
    'todo',
    __name__,
    template_folder='templates',
    static_folder='static'
)

@todo.get('/')
@login_required
def index():
    return render_template('todo/index.html')

@todo.get('/lottie/<path:filename>')
@login_required
def lottie_file(filename):
    return send_from_directory(current_app.config['UPLOAD_FOLDER'], filename)

@todo.get('/create')
@todo.post('/create')
@login_required
def create_todo():
    todos = UserTodo.query.filter_by(user_id=current_user.id).all()
    user = User.query.filter_by(id=current_user.id).first()
    user_path = user.user_path
    if todos == None:
        len_todo = 0
    len_todo = len(todos)
    print(len_todo)
    if len_todo >= 2 and user.is_admin == False:
        flash('目標は２つまでしか登録できません')
        return redirect(url_for('todo.todos', user_path=user_path))
    form = TodoCreateForm()
    print('form')
    if form.validate_on_submit():
        user_id=current_user.id
        todo_name=form.todo_name.data
        todo_pt=form.todo_pt.data
        todo_pt_result=form.todo_pt.data
        move_1=form.move_1.data
        move_2=form.move_2.data
        move_3=form.move_3.data
        move_4=form.move_4.data
        move_pt_1=form.move_pt_1.data
        move_pt_2=form.move_pt_2.data
        move_pt_3=form.move_pt_3.data
        move_pt_4=form.move_pt_4.data
        target_day=form.target_day.data
        reward=form.reward.data
        todo_path = generate_random_string()
        while True:
            if not UserTodo.query.filter_by(todo_path=todo_path).first():
                break
            todo_path = generate_random_string()
        
        todo = UserTodo(user_id=user_id, todo_name=todo_name, todo_pt=todo_pt, todo_pt_result=todo_pt_result, move_1=move_1, move_2=move_2, move_3=move_3, move_4=move_4, move_pt_1=move_pt_1, move_pt_2=move_pt_2, move_pt_3=move_pt_3, move_pt_4=move_pt_4, target_day=target_day, todo_path=todo_path, reward=reward)
        db.session.add(todo)
        db.session.commit()
        user = User.query.filter_by(id=current_user.id).first()
        user_path = user.user_path
        print('redirect')
        return redirect(url_for('todo.todos', user_path=user_path))
    return render_template('todo/create.html', form=form)

@todo.get('/<user_path>/<todo_path>/edit')
@todo.post('/<user_path>/<todo_path>/edit')
@login_required
def edit_todo(todo_path, user_path):
    form = TodoEditForm()
    todo = UserTodo.query.filter_by(todo_path=todo_path).first()
    if todo.user_id != current_user.id:
        return redirect(url_for('todo.todos', user_path=current_user.user_path))
    if form.validate_on_submit():
        todo.todo_name=form.todo_name.data
        todo.todo_pt=form.todo_pt.data
        todo.todo_pt_result=form.todo_pt_result.data
        todo.move_1=form.move_1.data
        todo.move_2=form.move_2.data
        todo.move_3=form.move_3.data
        todo.move_4=form.move_4.data
        todo.move_pt_1=form.move_pt_1.data
        todo.move_pt_2=form.move_pt_2.data
        todo.move_pt_3=form.move_pt_3.data
        todo.move_pt_4=form.move_pt_4.data
        todo.target_day=form.target_day.data
        todo.reward=form.reward.data

        user = User.query.filter_by(id=current_user.id).first()
        user_path = user.user_path

        if todo.todo_pt_result > todo.todo_pt:
            flash('現在ptは目標pt以下で入力してください')
            return redirect(url_for('todo.edit_todo', todo_path=todo.todo_path, user_path=user_path))
        
        db.session.add(todo)
        db.session.commit()
        return redirect(url_for('todo.todos', user_path=user_path))
    return render_template('todo/edit.html', todo=todo, form=form)

@todo.post('/<user_path>/<todo_path>/delete')
@login_required
def delete_todo(todo_path, user_path):
    todo = UserTodo.query.filter_by(todo_path=todo_path).first()
    if todo.user_id != current_user.id:
        return redirect(url_for('todo.todos', user_path=current_user.user_path))
    db.session.delete(todo)
    db.session.commit()
    return redirect(url_for('todo.todos', user_path=user_path))

@todo.get('/<user_path>/todos')
@todo.post('/<user_path>/todos')
@login_required
def todos(user_path):
    todos = UserTodo.query.filter_by(user_id=current_user.id).all()
    return render_template('todo/todos.html', todos=todos)

@todo.get('/<user_path>/<todo_path>/start')
@todo.post('/<user_path>/<todo_path>/start')
@login_required
def start_todo(todo_path, user_path):
    todo = UserTodo.query.filter_by(todo_path=todo_path).first()
    if todo.target_day:
        days_left = (todo.target_day - datetime.date.today()).days
    else:
        days_left = None
    print(todo.todo_name)
    if str(todo.user_id) != str(current_user.id):
        return redirect(url_for('todo.todos', user_path=current_user.user_path))
    if int(todo.todo_pt_result) <= 0:
        result_p = 0
    else:
        result_p = (todo.todo_pt_result / todo.todo_pt) * 100
    filename1 = 'AttAnim2'
    filename2 = 'AttAnim'
    filename3 = 'AttAnim3'
    filenameF = 'FinishAnim'
    return render_template('todo/start.html', todo=todo, result_p=result_p, filename1=filename1, filename2=filename2, filename3=filename3, filenameF=filenameF, days_left=days_left)

@todo.get('/update_pt')
@todo.post('/update_pt')
def update_pt():
    data = request.get_json()  # JSONデータを取得
    if not data:
        return jsonify({'message': 'データが受け取れませんでした'}), 400
    todo_id = data.get('id')  # todo_idを取得
    new_pt = int(data.get('pt'))
    
    # データベースから該当のTodoを取得
    todo = UserTodo.query.filter_by(id=todo_id).first()
    
    if todo:
        todo.todo_pt_result = new_pt  # ptを新しい値に更新
        db.session.add(todo)
        db.session.commit()  # データベースに保存
        return jsonify({'message': f"現在ポイントを {new_pt} に更新しました。"})
    else:
        return jsonify({'message': "Todoが見つかりませんでした。"}), 404
    
def generate_random_string(length=15):
    characters = string.ascii_letters + string.digits
    random_string = ''.join(random.choice(characters) for _ in range(length))
    return random_string

apps/todo/templates/todo/base.html
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bodymovin/5.7.6/lottie.min.js"></script>
    <link rel="stylesheet" href="{{ url_for('todo.static', filename='bootstrap.css') }}">
    <title>{% block title %}{% endblock %}</title>
</head>
<body class="m-3">
    <div>
        {% if current_user.is_authenticated %}
        <p class="top">
            <span><a class="link-secondary" href="{{ url_for('todo.index') }}">TOP</a>&nbsp;&nbsp;&nbsp;</span>
            <span>{{ current_user.username }}</span> - 
            <span><a class="link-secondary" href="{{ url_for('auth.logout') }}">ログアウト</a></span>
        </p>
        {% endif %}
    </div>
    {% block content %}
    {% endblock %}
</body>
</html>

apps/todo/templates/todo/create.html
{% extends 'todo/base.html' %}
{% block title %}目標を作成{% endblock %}
{% block content %}
<h2 class="top mb-3">目標を作成</h2>
<form
    action="{{ url_for('todo.create_todo') }}"
    method="POST"
    novalidate="novalidate"
>
    {{ form.csrf_token }}
    {% for error in form.target_day.errors %}
    <span style="color: red;">{{ error }}</span>
    {% endfor %}
    <p>
        {{ form.target_day.label }} <span>&nbsp;&nbsp;</span> {{ form.target_day(class='mb-2 date_pick', placeholder='目標期限')}}
    </p>
    {% for error in form.todo_name.errors %}
    <span style="color: red;">{{ error }}</span>
    {% endfor %}
    {% for error in form.todo_pt.errors %}
    <span style="color: red;">{{ error }}</span>
    {% endfor %}
    <p>
        {{ form.todo_name.label}} <span>&nbsp;</span> {{ form.todo_name(class='mb-2', placeholder='目標名')}} <span>&nbsp;&nbsp;&nbsp;</span> {{ form.todo_pt(class='mb-2', placeholder='目標pt')}}
    </p>
    {% for error in form.move_1.errors %}
    <span style="color: red;">{{ error }}</span>
    {% endfor %}
    {% for error in form.move_pt_1.errors %}
    <span style="color: red;">{{ error }}</span>
    {% endfor %}
    <p>
        {{ form.move_1.label}} <span>&nbsp;&nbsp;</span> {{ form.move_1(class='mb-2', placeholder='行動1')}} <span>&nbsp;&nbsp;&nbsp;</span> {{ form.move_pt_1(class='mb-2', placeholder='行動pt1')}}
    </p>

    {% for error in form.move_2.errors %}
    <span style="color: red;">{{ error }}</span>
    {% endfor %}
    {% for error in form.move_pt_2.errors %}
    <span style="color: red;">{{ error }}</span>
    {% endfor %}
    <p>
        {{ form.move_2.label}} <span>&nbsp;&nbsp;</span> {{ form.move_2(class='mb-2', placeholder='行動2')}} <span>&nbsp;&nbsp;&nbsp;</span> {{ form.move_pt_2(class='mb-2', placeholder='行動pt2')}}
    </p>

    {% for error in form.move_3.errors %}
    <span style="color: red;">{{ error }}</span>
    {% endfor %}
    {% for error in form.move_pt_3.errors %}
    <span style="color: red;">{{ error }}</span>
    {% endfor %}
    <p>
        {{ form.move_3.label}} <span>&nbsp;&nbsp;</span> {{ form.move_3(class='mb-2', placeholder='行動3')}} <span>&nbsp;&nbsp;&nbsp;</span> {{ form.move_pt_3(class='mb-2', placeholder='行動pt3')}}
    </p>

    {% for error in form.move_4.errors %}
    <span style="color: red;">{{ error }}</span>
    {% endfor %}
    {% for error in form.move_pt_4.errors %}
    <span style="color: red;">{{ error }}</span>
    {% endfor %}
    <p>
        {{ form.move_4.label}} <span>&nbsp;&nbsp;</span> {{ form.move_4(class='mb-2', placeholder='行動4')}} <span>&nbsp;&nbsp;&nbsp;</span> {{ form.move_pt_4(class='mb-2', placeholder='行動pt4')}}
    </p>

    {% for error in form.reward.errors %}
    <span style="color: red;">{{ error }}</span>
    {% endfor %}
    <p>
        {{ form.reward.label}} <span>&nbsp;&nbsp;</span> {{ form.reward(class='mb-2', placeholder='ご褒美')}}
    </p>
    <p>{{ form.submit(class='btn btn-indigo-light') }}</p>
</form>
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script>
    $(function() {
        $(".date_pick").datepicker({
            language: 'ja'
        });
    });
</script>
{% endblock %}

apps/todo/templates/todo/edit.html
{% extends 'todo/base.html' %}
{% block title %}目標を編集{% endblock %}
{% block content %}
<h3 class="top mb-3">目標を編集</h3>
<form
    action="{{ url_for('todo.edit_todo', todo_path=todo.todo_path, user_path=current_user.user_path) }}"
    method="POST"
    novalidate="novalidate"
>
    {{ form.csrf_token }}
    {% for message in get_flashed_messages() %}
    <p style="color: red;">{{ message }}</p>
    {% endfor %}

    {% for error in form.target_day.errors %}
    <span style="color: red;">{{ error }}</span>
    {% endfor %}
    <p>
        {{ form.target_day.label }} <span>&nbsp;&nbsp;</span> {{ form.target_day(class='mb-2 date_pick', placeholder='目標期限', value=todo.target_day) }}
    </p>
    
    {% for error in form.todo_name.errors %}
    <span style="color: red;">{{ error }}</span>
    {% endfor %}
    {% for error in form.todo_pt.error %}
    <span style="color: red;">{{ error }}</span>
    {% endfor %}
    <p>
        {{ form.todo_name.label }} <span>&nbsp;</span> {{ form.todo_name(class='mb-2', placeholder='目標名', value=todo.todo_name) }} <span>&nbsp;&nbsp;&nbsp;</span> {{ form.todo_pt(class='mb-2', placeholder='目標pt', value=todo.todo_pt) }}
    </p>
    <p></p>
        {{ form.todo_pt_result.label}} <span>&nbsp;</span> {{ form.todo_pt_result(class='mb-2', placeholder='現在pt', value=todo.todo_pt_result) }}
    </p>

    {% for error in form.move_1.error %}
    <span style="color: red;">{{ error }}</span>
    {% endfor %}
    {% for error in form.move_pt_1.error %}
    <span style="color: red;">{{ error }}</span>
    {% endfor %}
    <p></p>
        {{ form.move_1.label}} <span>&nbsp;&nbsp;</span> {{ form.move_1(class='mb-2', placeholder='行動1', value=todo.move_1) }} <span>&nbsp;&nbsp;&nbsp;</span> {{ form.move_pt_1(class='mb-2', placeholder='行動pt1', value=todo.move_pt_1) }}
    </p>
    

    {% for error in form.move_2.error %}
    <span style="color: red;">{{ error }}</span>
    {% endfor %}
    {% for error in form.move_pt_2.error %}
    <span style="color: red;">{{ error }}</span>
    {% endfor %}
    <p>
        {{ form.move_2.label}} <span>&nbsp;&nbsp;</span> {{ form.move_2(class='mb-2', placeholder='行動2', value=todo.move_2) }} <span>&nbsp;&nbsp;&nbsp;</span> {{ form.move_pt_2(class='mb-2', placeholder='行動pt2', value=todo.move_pt_2) }}
    </p>

    {% for error in form.move_3.error %}
    <span style="color: red;">{{ error }}</span>
    {% endfor %}
    {% for error in form.move_pt_3.error %}
    <span style="color: red;">{{ error }}</span>
    {% endfor %}
    <p>
        {{ form.move_3.label}} <span>&nbsp;&nbsp;</span> {{ form.move_3(class='mb-2', placeholder='行動3', value=todo.move_3) }} <span>&nbsp;&nbsp;&nbsp;</span> {{ form.move_pt_3(class='mb-2', placeholder='行動pt3', value=todo.move_pt_3) }}
    </p>

    {% for error in form.move_4.error %}
    <span style="color: red;">{{ error }}</span>
    {% endfor %}
    {% for error in form.move_pt_4.error %}
    <span style="color: red;">{{ error }}</span>
    {% endfor %}
    <p>
        {{ form.move_4.label}} <span>&nbsp;&nbsp;</span> {{ form.move_4(class='mb-2', placeholder='行動4', value=todo.move_4) }} <span>&nbsp;&nbsp;&nbsp;</span> {{ form.move_pt_4(class='mb-2', placeholder='行動pt4', value=todo.move_pt_4) }}
    </p>

    {% for error in form.reward.errors %}
    <span style="color: red;">{{ error }}</span>
    {% endfor %}
    <p>
        {{ form.reward.label}} <span>&nbsp;&nbsp;</span> {{ form.reward(class='mb-2', placeholder='ご褒美', value=todo.reward)}}
    </p>
    <p>{{ form.submit(class='btn btn-indigo-light') }}</p>
</form>
<form
    action="{{ url_for('todo.delete_todo', todo_path=todo.todo_path, user_path=current_user.user_path) }}"
    method="POST"
>
    {{ form.csrf_token }}
    <input type="submit" value="削除" class="btn btn-warning">
</form>
{% endblock %}

apps/todo/templates/todo/index.html
{% extends 'todo/base.html' %}
{% block title %}TODO{% endblock %}
{% block content %}
<div class="m-3">
    <a class="btn btn-lg btn-indigo-light shadow-sm" href="{{ url_for('todo.create_todo') }}" role="button">目標を作成</a>
</div>
<div class="m-3">
    <a class="btn btn-lg btn-indigo-light shadow-sm" href="{{ url_for('todo.todos', user_path=current_user.user_path) }}" role="button">目標一覧</a>
</div>
{% endblock %}

apps/todo/templates/todo/start.html
{% extends 'todo/base.html' %}
{% block title %}目標を進める{% endblock %}
{% block content %}
<input type="hidden" id="csrf_token" value="{{ csrf_token() }}">

{% if todo.target_day %}
    <h3 class="top">{{ todo.todo_name }} <span>&nbsp;&nbsp;</span> <span class="h4">{{ todo.target_day }}</span> <span>&nbsp;&nbsp;</span> <span><span class="h6">残り</span>{{ days_left }}<span class="h6">日</span></span></h3>
{% else %}
    <h3 class="top">{{ todo.todo_name }}</h3>
{% endif %}
{% if todo.reward %}
    <h5 class="top">ご褒美<span class="h4">「{{ todo.reward }}」</span></h5>
{% endif %}
<div class="progress w-50">
    <div class="progress-bar progress-bar-striped bg-info" id="myProgressBar" role="progressbar" aria-label="Basic example" aria-valuenow="{{ todo.todo_pt_result }}" aria-valuemin="0" aria-valuemax="{{ todo.todo_pt }}" style="width: {{ result_p }}%"></div>
</div>
<p class="top"><span id="todoPtResult">{{ todo.todo_pt_result }}</span> / {{ todo.todo_pt }}</p>
<div id="lottieAnimation1" class="lottie" style="width: 400px; height: 250;"></div>
<div id="lottieAnimation2" class="lottie" style="width: 400px; height: 250;"></div>
<div id="lottieAnimation3" class="lottie" style="width: 400px; height: 250;"></div>
<div id="lottieAnimation4" class="lottie" style="width: 400px; height: 250;"></div>
<div id="lottieAnimationF" class="lottie" style="width: 400px; height: 250;"></div>
<button type="button" class="btn btn-indigo-light mb-2" id="move1">{{ todo.move_1 }}</button>
<button type="button" class="btn btn-indigo-light mb-2" id="move2">{{ todo.move_2 }}</button>
<button type="button" class="btn btn-indigo-light mb-2" id="move3">{{ todo.move_3 }}</button>
<button type="button" class="btn btn-indigo-light mb-2" id="move4">{{ todo.move_4 }}</button>
<button id="updateButton" type="button" class="btn btn-indigo mb-2">行動を更新</button>

<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script>
    $(document).ready(function() {
        document.getElementById('lottieAnimationF').style.display = 'none';
        var lottie_filename = '{{ filenameF }}'
        var animationF = lottie.loadAnimation({
            container: document.getElementById('lottieAnimationF'), // アニメーションを表示する要素
            renderer: 'svg', // SVG形式で描画
            loop: false,      // ループ再生
            autoplay: false,  // 自動再生
            path: '{{ url_for("todo.lottie_file", filename="") }}' + lottie_filename + '.json' // Lottie JSONファイルのパス
        });

        document.getElementById('lottieAnimation1').style.display = 'none';
        var lottie_filename = '{{ filename1 }}'
        var animation1 = lottie.loadAnimation({
            container: document.getElementById('lottieAnimation1'), // アニメーションを表示する要素
            renderer: 'svg', // SVG形式で描画
            loop: false,      // ループ再生
            autoplay: false,  // 自動再生
            path: '{{ url_for("todo.lottie_file", filename="") }}' + lottie_filename + '.json' // Lottie JSONファイルのパス
        });

        document.getElementById('lottieAnimation2').style.display = 'none';
        var lottie_filename = '{{ filename2 }}'
        var animation2 = lottie.loadAnimation({
            container: document.getElementById('lottieAnimation2'), // アニメーションを表示する要素
            renderer: 'svg', // SVG形式で描画
            loop: false,      // ループ再生
            autoplay: false,  // 自動再生
            path: '{{ url_for("todo.lottie_file", filename="") }}' + lottie_filename + '.json' // Lottie JSONファイルのパス
        });

        document.getElementById('lottieAnimation3').style.display = 'none';
        var lottie_filename = '{{ filename3 }}'
        var animation3 = lottie.loadAnimation({
            container: document.getElementById('lottieAnimation3'), // アニメーションを表示する要素
            renderer: 'svg', // SVG形式で描画
            loop: false,      // ループ再生
            autoplay: false,  // 自動再生
            path: '{{ url_for("todo.lottie_file", filename="") }}' + lottie_filename + '.json' // Lottie JSONファイルのパス
        });
        animation3.setSpeed(1.3)

        document.getElementById('lottieAnimation4').style.display = 'none';
        var lottie_filename = '{{ filename2 }}'
        var animation4 = lottie.loadAnimation({
            container: document.getElementById('lottieAnimation4'), // アニメーションを表示する要素
            renderer: 'svg', // SVG形式で描画
            loop: false,      // ループ再生
            autoplay: false,  // 自動再生
            path: '{{ url_for("todo.lottie_file", filename="") }}' + lottie_filename + '.json' // Lottie JSONファイルのパス
        });
        $('#move1').click(function() {
            var todoPtResult = $('#todoPtResult').text();
            var movePt1 = {{ todo.move_pt_1|tojson }};
            var todoPt = {{ todo.todo_pt|tojson}};
            
            todoPtResult -= movePt1;
            if (todoPtResult <= 0) {
                todoPtResult = 0
            }
            if (todoPtResult <= 0) {
                document.getElementById('lottieAnimationF').style.display = 'block';
                animationF.goToAndStop(0, true); // アニメーションを最初から再生
                animationF.play();
            } else {
                document.getElementById('lottieAnimation1').style.display = 'block';
                animation1.goToAndStop(0, true); // アニメーションを最初から再生
                animation1.play();
            }
            newProgress = (todoPtResult / todoPt) * 100;
            $('#myProgressBar').css('width', newProgress + '%');
            $('#todoPtResult').text(todoPtResult);

            if (todoPtResult <= 0) {
                setTimeout(function () {
                    document.getElementById('lottieAnimationF').style.display = 'none';
                    animationF.stop();
                }, 3000);
            } else {
                setTimeout(function () {
                    document.getElementById('lottieAnimation1').style.display = 'none';
                    animation1.stop();
                }, 3000);
            }
        });

        $('#move2').click(function() {
            var todoPtResult = $('#todoPtResult').text();
            var movePt2 = {{ todo.move_pt_2|tojson }};
            var todoPt = {{ todo.todo_pt|tojson}};
            
            todoPtResult -= movePt2;
            if (todoPtResult <= 0) {
                todoPtResult = 0
            }
            if (todoPtResult <= 0) {
                document.getElementById('lottieAnimationF').style.display = 'block';
                animationF.goToAndStop(0, true); // アニメーションを最初から再生
                animationF.play();
            } else {
                document.getElementById('lottieAnimation2').style.display = 'block';
                animation2.goToAndStop(0, true); // アニメーションを最初から再生
                animation2.play();
            }
            newProgress = (todoPtResult / todoPt) * 100;
            $('#myProgressBar').css('width', newProgress + '%');
            $('#todoPtResult').text(todoPtResult);

            if (todoPtResult <= 0) {
                setTimeout(function () {
                    document.getElementById('lottieAnimationF').style.display = 'none';
                    animationF.stop();
                }, 3000);
            } else {
                setTimeout(function () {
                    document.getElementById('lottieAnimation2').style.display = 'none';
                    animation2.stop();
                }, 3000);
            }
        });

        $('#move3').click(function() {
            var todoPtResult = $('#todoPtResult').text();
            var movePt3 = {{ todo.move_pt_3|tojson }};
            var todoPt = {{ todo.todo_pt|tojson}};
            
            todoPtResult -= movePt3;
            if (todoPtResult <= 0) {
                todoPtResult = 0
            }
            if (todoPtResult <= 0) {
                document.getElementById('lottieAnimationF').style.display = 'block';
                animationF.goToAndStop(0, true); // アニメーションを最初から再生
                animationF.play();
            } else {
                document.getElementById('lottieAnimation3').style.display = 'block';
                animation3.goToAndStop(0, true); // アニメーションを最初から再生
                animation3.play();
            }
            newProgress = (todoPtResult / todoPt) * 100;
            $('#myProgressBar').css('width', newProgress + '%');
            $('#todoPtResult').text(todoPtResult);

            if (todoPtResult <= 0) {
                setTimeout(function () {
                    document.getElementById('lottieAnimationF').style.display = 'none';
                    animationF.stop();
                }, 3000);
            } else {
                setTimeout(function () {
                    document.getElementById('lottieAnimation3').style.display = 'none';
                    animation3.stop();
                }, 3000);
            }
        });

        $('#move4').click(function() {
            var todoPtResult = $('#todoPtResult').text();
            var movePt4 = {{ todo.move_pt_4|tojson }};
            var todoPt = {{ todo.todo_pt|tojson}}
            
            todoPtResult -= movePt4;
            if (todoPtResult <= 0) {
                todoPtResult = 0
            }
            if (todoPtResult <= 0) {
                document.getElementById('lottieAnimationF').style.display = 'block';
                animationF.goToAndStop(0, true); // アニメーションを最初から再生
                animationF.play();
            } else {
                document.getElementById('lottieAnimation4').style.display = 'block';
                animation4.goToAndStop(0, true); // アニメーションを最初から再生
                animation4.play();
            }
            newProgress = (todoPtResult / todoPt) * 100;
            $('#myProgressBar').css('width', newProgress + '%');
            $('#todoPtResult').text(todoPtResult);

            if (todoPtResult <= 0) {
                setTimeout(function () {
                    document.getElementById('lottieAnimationF').style.display = 'none';
                    animationF.stop();
                }, 3000);
            } else {
                setTimeout(function () {
                    document.getElementById('lottieAnimation4').style.display = 'none';
                    animation4.stop();
                }, 3000);
            }
        });
        function updateTodoPtResult() {
            var newPt = document.getElementById('todoPtResult').textContent;
            var todoId = {{ todo.id|tojson }};
            var csrfToken = $('#csrf_token').val();
            const url = '{{ url_for("todo.update_pt") }}'
            console.log(newPt)
    
            // fetchを使用してデータを送信
            fetch('/todo/update_pt', {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json',
                    'X-CSRFToken': csrfToken
                },
                body: JSON.stringify({
                    pt: newPt,
                    id: todoId
                })
            })
            .then(response => response.json())
            .then(data => {
                // サーバーからのレスポンスを表示
                alert(data.message);
            })
            .catch(error => {
                console.error('エラー:', error);
            });
        }
        $('#updateButton').click(updateTodoPtResult);
    });
</script>
{% endblock %}

apps/todo/templates/todo/todos.html
{% extends 'todo/base.html' %}
{% block title %}目標を進める{% endblock %}
{% block content %}
<h3 class="top mb-3">目標一覧</h3>
{% for message in get_flashed_messages() %}
<p style="color: red;">{{ message }}</p>
{% endfor %}
{% for todo in todos %}
<div class="mb-3">
    <a class="btn btn-lg btn-indigo-light" href="{{ url_for('todo.start_todo', todo_path=todo.todo_path, user_path=current_user.user_path) }}" role="button">{{ todo.todo_name }}</a>
    <span>&nbsp;</span>
    <a class="btn btn-lg btn-indigo-light" href="{{ url_for('todo.edit_todo', todo_path=todo.todo_path, user_path=current_user.user_path) }}" role="button">編集</a>
</div>
{% endfor %}
{% endblock %}