apps/crud/models.py
from datetime import datetime
from apps.app import db, login_manager
from flask_login import UserMixin
from werkzeug.security import generate_password_hash, check_password_hash

class User(db.Model, UserMixin):
    __tablename__ = 'users'
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String, index=True)
    email = db.Column(db.String, unique=True, index=True)
    password_hash = db.Column(db.String)
    user_path = db.Column(db.String)
    is_admin = db.Column(db.Boolean, nullable=False, default=0)
    created_at = db.Column(db.DateTime, default=datetime.now)
    updated_at = db.Column(db.DateTime, default=datetime.now, onupdate=datetime.now)
    todos = db.relationship('UserTodo', backref='user')

    @property
    def password(self):
        raise AttributeError('読み取り不可')
    
    @password.setter
    def password(self, password):
        self.password_hash = generate_password_hash(password)

    def verify_password(self, password):
        return check_password_hash(self.password_hash, password)
    
    def is_duplicate_email(self):
        return User.query.filter_by(email=self.email).first() is not None
    
@login_manager.user_loader
def load_user(user_id):
    return User.query.get(user_id)

apps/crud/forms.py
from flask_wtf import FlaskForm
from wtforms import PasswordField, StringField, SubmitField
from wtforms.validators import DataRequired, Email, length

class UserForm(FlaskForm):
    username = StringField(
        'ユーザー名',
        validators=[
            DataRequired(message='ユーザー名は必須です。'),
            length(max=30, message='30文字以内で入力してください')
        ]
    )
    email = StringField(
        'メールアドレス',
        validators=[
            DataRequired(message='メールアドレスは必須です。'),
            Email(message='メールアドレスの形式で入力してください。')
        ]
    )
    password = PasswordField(
        'パスワード',
        validators=[
            DataRequired(message='パスワードは必須です。')
        ]
    )
    submit = SubmitField('新規登録')

apps/crud/__init__.py
import apps.crud.models

apps/crud/views.py
from flask import Blueprint, render_template, redirect, url_for
from apps.app import db
from apps.crud.models import User
from apps.crud.forms import UserForm
from flask_login import login_required, current_user

crud = Blueprint(
    'crud',
    __name__,
    template_folder='templates',
    static_folder='static'
)

@crud.get('/users')
@login_required
def users():
    if current_user.is_admin == False:
        return render_template('todo/index.html')
    users = User.query.all()
    return render_template('crud/index.html', users=users)

@crud.get('/users/<user_id>')
@crud.post('/users/<user_id>')
@login_required
def edit_user(user_id):
    if current_user.is_admin == False:
        return render_template('todo/index.html')
    form = UserForm()
    user = User.query.filter_by(id=user_id).first()
    if form.validate_on_submit():
        user.username = form.username.data
        user.email = form.email.data
        user.password = form.password.data
        db.session.add(user)
        db.session.commit()
        return redirect(url_for('crud.users'))
    return render_template('crud/edit.html', user=user, form=form)

@crud.post('/users/<user_id>/delete')
@login_required
def delete_user(user_id):
    if current_user.is_admin == False:
        return render_template('todo/index.html')
    user = User.query.filter_by(id=user_id).first()
    db.session.delete(user)
    db.session.commit()
    return redirect(url_for('crud.users'))

apps/crud/templates/crud/base.html
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    <div>
        {% if current_user.is_authenticated %}
        <p>
            <span>{{ current_user.username }}</span> - 
            <span><a href="{{ url_for('auth.logout') }}">ログアウト</a></span>
        </p>
        {% endif %}
    </div>
    {% block content %}
    {% endblock %}
</body>
</html>

apps/crud/templates/crud/create.html
{% extends 'crud/base.html' %}
{% block title %}ユーザー新規作成{% endblock %}
{% block content %}
<h2>ユーザー新規作成</h2>
<form
    action="{{ url_for('crud.create_user')}}",
    method="POST",
    novalidate="novalidate"
>
    {{ form.csrf_token }}
    <p>
        {{ form.username.label}} {{ form.username(placeholder='ユーザー名')}}
    </p>
    {% for error in form.username.error %}
    <span style="color: red;">{{ error }}</span>
    {% endfor %}
    <p>
        {{ form.email.label}} {{ form.email(placeholder='メールアドレス')}}
    </p>
    {% for error in form.email.error %}
    <span style="color: red;">{{ error }}</span>
    {% endfor %}
    <p>
        {{ form.password.label}} {{ form.password(placeholder='パスワード')}}
    </p>
    {% for error in form.password.error %}
    <span style="color: red;">{{ error }}</span>
    {% endfor %}
    <p>{{ form.submit() }}</p>
</form>
{% endblock %}

apps/crud/templates/crud/edit.html
{% extends 'crud/base.html' %}
{% block title %}ユーザー編集{% endblock %}
{% block content %}
<h2>ユーザー編集</h2>
<form
    action="{{ url_for('crud.edit_user', user_id=user.id) }}"
    method="POST"
    novalidate="novalidate"
>
{{ form.csrf_token }}
<p>
    {{ form.username.label }} {{ form.username(placeholder='ユーザー名', value=user.username )}}
</p>
{% for error in form.username.errors %}
<span style="color: red;">{{ error }}</span>
{% endfor %}

<p>
    {{ form.email.label }} {{ form.email(placeholder='メールアドレス', value=user.email )}}
</p>
{% for error in form.email.errors %}
<span style="color: red;">{{ error }}</span>
{% endfor %}

<p>
    {{ form.password.label }} {{ form.password(placeholder='パスワード', value=user.password )}}
</p>
{% for error in form.password.errors %}
<span style="color: red;">{{ error }}</span>
{% endfor %}

<p><input type="submit" value="更新"></p>
</form>
<form
    action="{{ url_for('crud.delete_user', user_id=user.id) }}"
    method="POST"
>
{{ form.csrf_token }}
<input type="submit" value="削除">
</form>
{% endblock %}

apps/crud/templates/crud/index.html
{% extends 'crud/base.html' %}
{% block title %}タイトル{% endblock %}
{% block content %}
<h2>ユーザー一覧</h2>

<table class="table table-primary table-striped">
    <tr>
        <td>ユーザーID</td>
        <td>ユーザー名</td>
        <td>メールアドレス</td>
        <td>アドミン</td>
        <td>ユーザーパス</td>
    </tr>
    {% for user in users %}
    <tr>
        <td>
            <a href="{{ url_for('crud.edit_user', user_id=user.id) }}">{{ user.id }}</a>
        </td>
        <td>{{ user.username }}</td>
        <td>{{ user.email }}</td>
        <td>{{ user.is_admin }}</td>
        <td>{{ user.user_path }}</td>
    </tr>
    {% endfor %}
</table>
{% endblock %}